core/urls.py
from django.urls import path

from .views import anuncio, home, index

urlpatterns = [
    path('', index, name='index'),
    path('relogio/', anuncio, name='anuncio_individual'),
    path('', home, name='homepage')
]

projetofront/urls.py
#from django.contrib import admin
from django.urls import path, include

# Urls Includes
from core import urls as core_urls
from authentication import urls as auth_urls
from user import urls as user_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(core_urls)),
    path('auth/', include(auth_urls)),
    path('user/', include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import index, user_data, orders, products, addresses, add_product

# Endereços
from .views import create_address, update_address, destroy_address

# Cartões
from .views import create_credit_card, update_card, destroy_card

# Produtos
from .views import show_products, create_product, update_product, destroy_product

urlpatterns = [
    path('', index, name='user_index'),
    path('meusdados/', user_data, name='user_data'),
    path('pedidos/', orders, name='user_orders'),
    #path('meusprodutos/', products, name='user_products'),
    #path('meusprodutos/adicionarproduto/', add_product, name='user_add_product'),
    #path('enderecos/', addresses, name='user_addresses'),

    # Endereços
    path('enderecos/', create_address, name='user_addresses'),
    path('enderecos/atualizar/<uuid:id>', update_address, name='update_address'),
    path('enderecos/apagar/<uuid:id>', destroy_address, name='destroy_address'),

    # Cartões
    path('meuscartoes/', create_credit_card, name='user_cards'),
    path('meuscartoes/atualizar/<uuid:id>', update_card, name='update_card'),
    path('meuscartoes/apagar/<uuid:id>', destroy_card, name='destroy_card'),

    # Produtos
    path('meusprodutos/', show_products, name='user_products'),
    path('meusprodutos/adicionar/', create_product, name='add_product'),
    #path('meusprodutos/detalhar/<uuid:id>', product_detail, name='product_detail'),
    path('meusprodutos/atualizar/<uuid:id>', update_product, name='update_product'),
    path('meusprodutos/apagar/<uuid:id>', destroy_product, name='destroy_product'),

] 

user/models.py
import uuid
from django.db import models

# https://www.watchdepot.com.au/types-of-watches
CATEGORIES = (
    ('AV', 'Aviador'),
    ('ML', 'Militar'),
    ('CR', 'Corredor'),
    ('MR', 'Mergulhador'),
    ('CM', 'Campo'),
    ('FS', 'Fashion'),
    ('LX', 'Luxuoso'),
    ('ST', 'Smart'),
    ('FT', 'Fitness'),
    ('BS', 'Bolso'),
    ('MD', 'Médico'),
    ('ES', 'Esportivo'),
    ('RS', 'Rústico'),
    ('FR', 'Formal'),
)

BRANDS = (
    ('AR', 'Armani'),
    ('CT', 'Cartier'),
    ('CS', 'Casio'),
    ('CP', 'Champion'),
    ('MB', 'Montblanc'),
    ('MM', 'Mormaii'),
    ('RX', 'Rolex'),
    ('TH', 'Tommy Hilfighter'),
    ('WP', 'Wempe'),
)

class Product(models.Model):
    id = models.UUIDField("Id", primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField("Nome", max_length=100)
    price = models.DecimalField("Preço", max_digits=5, decimal_places=2)
    brand = models.CharField("Marca", max_length=2, choices=BRANDS)
    description = models.TextField("Descrição")
    category = models.CharField("Categoria", max_length=2, choices=CATEGORIES)
    total_sales = models.IntegerField("Total Sales", default=0)

class ProductImage(models.Model):
    name = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    default = models.BooleanField(default=False)


STATES = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )

# Endereços e afins
class Address(models.Model):
    id = models.UUIDField("Id", primary_key=True, default=uuid.uuid4, editable=False)
    zip = models.IntegerField('Cep')
    public_place = models.CharField('Logradouro', max_length=50)
    number = models.IntegerField('Número')
    complement = models.CharField('Complemento', max_length=100)
    reference = models.CharField('Referência', max_length=100)
    neighborhood = models.CharField('Bairro', max_length=100)
    city = models.CharField('Cidade', max_length=50)
    state = models.CharField("Estado", max_length=2, choices=STATES)
    description = models.CharField('Cidade', max_length=60)
    is_main = models.BooleanField(blank=True)


# Cartões e afins
class CreditCard(models.Model):
    id = models.UUIDField("Id", primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.CharField("Portador", max_length=100)
    number = models.IntegerField("Número do cartão")
    valid_until = models.CharField("Válidade", max_length=20)
    cvv = models.IntegerField("Código de verificação")

user/forms.py
from django import forms  
from .models import Address, CreditCard, Product 

class AddressForm(forms.ModelForm):  
    class Meta:  
        model = Address  
        fields = [
            "description",
            "zip",
            "public_place",
            "number",
            "complement",
            "reference",
            "neighborhood",
            "city",
            "state",
            "is_main",
        ]  


class CreditCardForm(forms.ModelForm):  
    class Meta:  
        model = CreditCard  
        fields = [
            "owner",
            "number",
            "valid_until",
            "cvv"
        ] 


class ProductForm(forms.ModelForm):  
    class Meta:  
        model = Product  
        fields = [
            "name",
            "price",
            "brand",
            "description",
            "category",
        ] 

user/views.py
from django.shortcuts import render, redirect
from .forms import AddressForm, CreditCardForm, ProductForm
from .models import Address, CreditCard, Product, ProductImage  


# Create your views here.
def index(request):
    return render(request, 'user.html')

def user_data(request):
    return render(request, 'personal.html')

def orders(request):
    return render(request, 'orders.html')

def products(request):
    return render(request, 'my_products.html')

def addresses(request):
    return render(request, 'address.html')

def add_product(request):
    return render(request, 'add_product.html')


# Address views
def create_address(request):
    print("acessando addresses")
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('user_addresses')
            except:
                pass
    else:
        addresses = Address.objects.all() 
        form = AddressForm()
     
    context = {
        "addresses": addresses,
        "form": form
    }

    return render(request, 'address.html', context)


def update_address(request, id):  
    address = Address.objects.get(id=id)  
    form = AddressForm(request.POST, instance=address)  
    
    if form.is_valid():  
        form.save()  
        return redirect("user_addresses")  
    
    context = {
        "address": address,
        "addresses": Address.objects.all(),
        "form": form
    }
    return render(request, 'address_edit.html', context)  


def destroy_address(request, id):  
    address = Address.objects.get(id=id)  
    address.delete()  
    return redirect("user_addresses")  



# Credit card views
def create_credit_card(request):
    if request.method == "POST":
        
        form = CreditCardForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('user_cards')
            except:
                pass
    else:
        cards = CreditCard.objects.all() 
        form = CreditCardForm()
     
    context = {
        "cards": cards,
        "form": form
    }

    return render(request, 'cards.html', context)


def update_card(request, id):  
    card = CreditCard.objects.get(id=id)  
    form = CreditCardForm(request.POST, instance=card)  
    
    if form.is_valid():  
        form.save()  
        return redirect("user_cards")  
    
    context = {
        "card": card,
        "cards": CreditCard.objects.all(),
        "form": form
    }
    return render(request, 'card_edit.html', context)  


def destroy_card(request, id):  
    card = CreditCard.objects.get(id=id)  
    card.delete()  
    return redirect("user_cards")  


# Product views
def show_products(request):
    products = Product.objects.all()
    context = {
        "products": products
    }
    return render(request, 'products_show.html', context)


def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        images = request.FILES.getlist('images')
        if form.is_valid():
            try:
                new_product= form.save()
                for image in images:
                    ProductImage.objects.create(name=image.name, product=new_product, image=image)

                return redirect('user_products')
            except:
                pass
    else:
        form = ProductForm()
     
    context = {
        "form": form
    }

    return render(request, 'product_add.html', context)


def update_product(request, id):  
    product = Product.objects.get(id=id)  
    form = ProductForm(request.POST, instance=product)
    images = ProductImage.objects.filter(product=product)
    new_images = request.FILES.getlist('images') or []

    if form.is_valid():  
        form.save()
        for image in new_images:
            ProductImage.objects.create(name=image.name, product=product, image=image)
        return redirect("user_products")  
    
    context = {
        "product": product,
        "form": form,
        "images": images
    }
    return render(request, 'product_edit.html', context)  


def destroy_product(request, id):  
    product = Product.objects.get(id=id)  
    product.delete()  
    return redirect("user_products") 

user/templates/address.html
{% extends "user_base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Meus endereços{% endblock %}

{% block content %}
<main class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'user_index' %}">Início</a></li>
      <li class="breadcrumb-item" aria-current="page"><span class="badge bg-warning rounded-pill">Endereços</span></li>
    </ol>
  </nav>
  <div class="row">
    <div class="col-md-8 col-lg-8 mb-3">
      <h4 class="mb-3">ADICIONAR ENDEREÇO</h4>
      <div class="card p-3">
        <form class="needs-validation" action="{% url 'user_addresses' %}" method="POST" enctype="multipart/form-data" >
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          <div class="row g-3">
            <div class="col-md-12">
              <label for="description" class="form-label">Descrição *</label>
              {% render_field form.description class+="form-control" placeholder="Descrição do endereço" %}
              <div class="invalid-feedback">
                {{ form.description.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="zip" class="form-label">CEP *</label>
              {% render_field form.zip class+="form-control" placeholder="00000-000" %}
              <div class="invalid-feedback">
                {{ form.zip.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="address" class="form-label">Logradouro *</label>
              {% render_field form.public_place class+="form-control" placeholder="Rua Correia de Lemos" %}
              <div class="invalid-feedback">
                {{ form.public_place.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="number" class="form-label">Número *</label>
              {% render_field form.number class+="form-control" placeholder="Número" %}
              <div class="invalid-feedback">
                {{ form.number.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="complement" class="form-label">Complemento</label>
              {% render_field form.complement class+="form-control" placeholder="Número" %}
              <div class="invalid-feedback">
                {{ form.complement.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="reference" class="form-label">Referência</label>
              {% render_field form.reference class+="form-control" placeholder="Ao lado da padaria" %}
              <div class="invalid-feedback">
                {{ form.reference.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="neighborhood" class="form-label">Bairro *</label>
              {% render_field form.neighborhood class+="form-control" placeholder="Bairro" %}
              <div class="invalid-feedback">
                {{ form.neighborhood.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="city" class="form-label">Cidade *</label>
              {% render_field form.city class+="form-control" placeholder="Cidade" %}
              <div class="invalid-feedback">
                {{ form.city.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="state" class="form-label">UF</label>
              {% render_field form.state class+="form-control" %}
              <div class="invalid-feedback">
                {{ form.state.errors }}
              </div>
            </div>
          </div>
          <div class="form-check mt-3 mb-3">
            {% render_field form.is_main class+="form-check-input" %}
            <label class="form-check-label" for="default-address">Esse é o meu endereço principal</label>
          </div>
          <button class="w-100 btn btn-warning btn-lg mb-3" type="submit">Salvar endereço <span data-feather="arrow-right"></span></button>
        </form>
      </div>
      
    </div>
    <div class="col-md-4 col-lg-4">
      <h4 class="mb-3">ENDEREÇOS CADASTRADOS <span data-feather="home"></span></h4>
      {% for address in addresses %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ address.description }} {{ address.is_main|yesno:"(Principal)," }}</h5>
          <p class="card-text">{{ address.public_place }}, n° {{ address.number }}<br> 
            {{ address.neighborhood }} - {{ address.city }}, {{ address.state }} <br> 
            {{ address.zip }} <br>
          </p>
          <a href="{% url 'update_address' address.id %}" class="link-warning custom-link">Editar</a> <a href="{% url 'destroy_address' address.id %}" class="link-danger custom-link">Excluir</a>
        </div>
      </div>
      {% empty %}
        <li>Nenhum endereço cadastrado</li>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock %}

user/templates/address_edit.html
{% extends "user_base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Meus endereços{% endblock %}

{% block content %}
<main class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'user_index' %}">Início</a></li>
      <li class="breadcrumb-item" aria-current="page"><span class="badge bg-warning rounded-pill">Endereços</span></li>
    </ol>
  </nav>
  <div class="row">
    <div class="col-md-8 col-lg-8 mb-3">
      <h4 class="mb-3">ADICIONAR ENDEREÇO</h4>
      <div class="card p-3">
        <form class="needs-validation" action="{% url 'update_address' address.id %}" method="POST" enctype="multipart/form-data" >
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          <div class="row g-3">
            <div class="col-md-12">
              <label for="description" class="form-label">Descrição * {{ address.description }}</label>
              {% render_field form.description class+="form-control" value=address.description placeholder="Descrição do endereço" %}
              <div class="invalid-feedback">
                {{ form.description.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="zip" class="form-label">CEP *</label>
              {% render_field form.zip class+="form-control" value=address.zip placeholder="00000-000" %}
              <div class="invalid-feedback">
                {{ form.zip.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="address" class="form-label">Logradouro *</label>
              {% render_field form.public_place class+="form-control" value=address.public_place placeholder="Rua Correia de Lemos" %}
              <div class="invalid-feedback">
                {{ form.public_place.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="number" class="form-label">Número *</label>
              {% render_field form.number class+="form-control" value=address.number placeholder="Número" %}
              <div class="invalid-feedback">
                {{ form.number.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="complement" class="form-label">Complemento</label>
              {% render_field form.complement class+="form-control" value=address.complement placeholder="Número" %}
              <div class="invalid-feedback">
                {{ form.complement.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="reference" class="form-label">Referência</label>
              {% render_field form.reference class+="form-control" value=address.reference placeholder="Ao lado da padaria" %}
              <div class="invalid-feedback">
                {{ form.reference.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="neighborhood" class="form-label">Bairro *</label>
              {% render_field form.neighborhood class+="form-control" value=address.neighborhood placeholder="Bairro" %}
              <div class="invalid-feedback">
                {{ form.neighborhood.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="city" class="form-label">Cidade *</label>
              {% render_field form.city class+="form-control" value=address.city placeholder="Cidade" %}
              <div class="invalid-feedback">
                {{ form.city.errors }}
              </div>
            </div>
            <div class="col-md-6">
              <label for="state" class="form-label">UF</label>
              
              <select id="{{ form.state.id }}" class="form-control" name="{{ form.state.name }}">
                {% for choice in form.state.field.choices %}
                    {% if choice.0 == address.state %}
                      <option value="{{ choice.0 }}" selected="selected">{{ choice.1 }}</option>
                    {% else %}
                      <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endif %}    
                {% endfor %}
              </select>
              <div class="invalid-feedback">
                {{ form.state.errors }}
              </div>
            </div>
          </div>
          <div class="form-check mt-3 mb-3">
            {% render_field form.is_main class+="form-check-input" checked=address.is_main %}
            <label class="form-check-label fs-6" for="id_is_main">Esse é o meu endereço principal</label>
          </div>
          <button class="w-100 btn btn-warning btn-lg mb-3" type="submit">Salvar endereço <span data-feather="arrow-right"></span></button>
        </form>
      </div>
      
    </div>
    <div class="col-md-4 col-lg-4">
      <h4 class="mb-3">ENDEREÇOS CADASTRADOS <span data-feather="home"></span></h4>
      {% for address in addresses %}
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ address.description }} {{ address.is_main|yesno:"(Principal)," }}</h5>
          <p class="card-text">{{ address.public_place }}, n° {{ address.number }}<br> 
            {{ address.neighborhood }} - {{ address.city }}, {{ address.state }} <br> 
            {{ address.zip }} <br>
          </p>
          <a href="{% url 'update_address' address.id %}" class="link-warning custom-link">Editar</a> <a href="{% url 'destroy_address' address.id %}" class="link-danger custom-link">Excluir</a>
        </div>
      </div>
      {% empty %}
        <li>Nenhum endereço cadastrado</li>
      {% endfor %}
    </div>
  </div>
</main>
{% endblock %}

user/templates/my_products.html
{% extends "user_base.html" %}
{% load static %}

{% block title %}Meus produtos{% endblock %}

{% block content %}
<main class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'user_index' %}">Início</a></li>
      <li class="breadcrumb-item" aria-current="page"><span class="badge bg-warning rounded-pill">Produtos</span></li>
    </ol>
  </nav>
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <h4 class="mb-3 card-title ">Meus produtos <span data-feather="shopping-cart"></span> <a class="btn btn-warning float-end" href="{% url 'user_add_product' %}" style="color: #fff;">Adicionar</a></h4>
      <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Relógio da xuxa</div>
            208 vendas na última semana
          </div>
          <span class="badge bg-warning rounded-pill">208</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Relógio Mormaii digital</div>
            124 vendas na última semana
          </div>
          <span class="badge bg-warning rounded-pill">124</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Relógio Rolex Submariner</div>
            14 vendas na última semana
          </div>
          <span class="badge bg-warning rounded-pill">14</span>
        </li>
      </ol>
    </div>
  </div>
  <nav class="mt-3">
    <ul class="pagination justify-content-center">
      <li class="page-item disabled">
        <a class="page-link">Anterior</a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#">Próximo</a>
      </li>
    </ul>
  </nav>
</main>
{% endblock %}

user/templates/product_edit.html
{% extends "user_base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Início{% endblock %}

{% block optional_static %}
<!-- Filepond stylesheet -->
<link href="https://unpkg.com/filepond@^4/dist/filepond.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<main class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'user_index' %}">Início</a></li>
      <li class="breadcrumb-item"><a href="{% url 'user_products' %}">Meus produtos</a></li>
      <li class="breadcrumb-item" aria-current="page"><span class="badge bg-warning rounded-pill">Adicionar Produto</span></li>
    </ol>
  </nav>
  <h4 class="card-title mb-3">Adicionar produto <span data-feather="edit"></span></h4>
  <div class="card p-3">
    
    <div class="row">
        <div class="col-md-12">
            <form class="needs-validation" action="{% url 'update_product' product.id %}" method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                <div class="row gy-3 mb-3">
                    <div class="col-md-6">
                        <label for="cc-name" class="form-label">Nome do produto</label>
                        {% render_field form.name class+="form-control" value=product.name placeholder="Nome do produto aqui" %}
                        <small class="text-muted">Nome que aparecerá no título do anúncio</small>
                        <div class="invalid-feedback">
                            {{ form.name.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="cc-number" class="form-label">Preço</label>
                        {% render_field form.price class+="form-control" value=product.price placeholder="R$ 00.000,00" %}
                        <small class="text-muted">Digite apenas números</small>
                        <div class="invalid-feedback">
                            {{ form.price.errors }}
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <label for="cc-brand" class="form-label">Marca</label>
                        <select id="{{ form.brand.id }}" class="form-control" name="{{ form.brand.name }}">
                            {% for choice in form.brand.field.choices %}
                                {% if choice.0 == product.brand %}
                                  <option value="{{ choice.0 }}" selected="selected">{{ choice.1 }}</option>
                                {% else %}
                                  <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                {% endif %}    
                            {% endfor %}
                        </select>
                        <div class="invalid-feedback">
                            {{ form.brand.errors }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="cc-color" class="form-label">Categoria</label>
                        <select id="{{ form.category.id }}" class="form-control" name="{{ form.category.name }}">
                            {% for choice in form.category.field.choices %}
                                {% if choice.0 == product.category %}
                                  <option value="{{ choice.0 }}" selected="selected">{{ choice.1 }}</option>
                                {% else %}
                                  <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                {% endif %}    
                            {% endfor %}
                        </select>
                        <div class="invalid-feedback">
                            {{ form.category.errors }}
                        </div>
                    </div>

                    <div class="col-md-12">
                        <label for="cc-number" class="form-label">Descrição</label>
                        <textarea name="description" cols="40" rows="10" class="form-control" placeholder="Descrição do produto" required="" id="id_description">{{ product.description }}</textarea>
                        <small class="text-muted">Dê o máximo de detalhes o possível do seu produto</small>
                        <div class="invalid-feedback">
                            {{ form.description.errors }}
                        </div>
                    </div>

                    <div class="col-md-12">
                        <label for="cc-number" class="form-label">Fotos do produto</label>
                        <input id="product-images" class="form-control" type="file" name="images" multiple>
                        <small class="text-muted">Escolha boas imagens para o seu produto</small>
                        <div class="invalid-feedback">
                        </div>
                    </div>
                </div>
    
                <div class="input-images"></div>
                <a class="mt-4 btn btn-danger btn-lg float-end ms-2" href="{% url 'destroy_product' product.id %}">Excluir</a>
                <input class="mt-4 btn btn-warning btn-lg float-end" type="submit" value="Atualizar">  
            </form>
            <div>
                {% for image in images %}
                    <img width="200" height="200" src="{{ image.image.url }}" class="img-thumbnail" alt="">
                {% endfor %}
            </div>
        </div>
    </div>
  </div>
</main>
{% endblock %}

{% block optional_scripts %} 
<script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>
<script src="{% static 'js/pond_pt_br.js' %}"></script>

<script>
    const inputElement = document.querySelector('input[type="file"]');
    // Create a FilePond instance
    //const pond = FilePond.create(inputElement);
    //FilePond.parse(document.body);
    //console.log(window);
  
    //const pt_br = window["pt-br"];
    //FilePond.setOptions(config);
</script>

{% endblock %}